### ISSUE TITLE
cannot find function `write_str_simd` in this scope

### ISSUE THREAD

**Issue by universalmind303** [simd-lite/value-trait#26]
crate errors out when compiling to `armv7-unknown-linux-gnueabihf` with the following error:

```
error[E0425]: cannot find function `write_str_simd` in this scope
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/value-trait-0.4.0/src/generator.rs:162:19
    |
162 |             stry!(write_str_simd(self.get_writer(), &mut string,));
    |                   ^^^^^^^^^^^^^^ not found in this scope
```

**Comment by universalmind303** [comment]
looks like its related to that function not being implemented for `arm` arch.

**Comment by philss** [comment]
I got the same error while trying to compile against the `arm-unknown-linux-gnueabihf` target.

I could reproduce with [`cross`](https://github.com/cross-rs/cross):

```
$ cross build --target=arm-unknown-linux-gnueabihf
```

**Comment by gyscos** [comment]
It's also not currently implemented for any riscv64 target.

Each implementation of this function is gated on a specific architecture. I suggest at least adding an implementation gated on the negation of all other cases, that would result in a better compilation error ("this architecture is not supported") rather than the current error.
